{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.secretStores }}
{{- range $store := .Values.externalSecrets.secretStores }}
---
apiVersion: external-secrets.io/v1
kind: {{ default "ClusterSecretStore" $store.kind }}
metadata:
  name: {{ required "externalSecrets.secretStores[].name is required" $store.name }}
  {{- if and (eq (default "ClusterSecretStore" $store.kind) "SecretStore") $store.namespace }}
  namespace: {{ $store.namespace }}
  {{- end }}
  {{- with $store.labels }}
  labels:
{{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with $store.annotations }}
  annotations:
{{ toYaml . | nindent 4 }}
  {{- end }}
spec:{{ toYaml (required "externalSecrets.secretStores[].spec is required" $store.spec) | nindent 2 }}
{{- end }}
{{- end }}
