apiVersion: 1

datasources:
  # Prometheus - EC2 장기 보관 (30d)
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "30s"
      queryTimeout: "60s"
      httpMethod: POST

  # Tempo - K8s in-cluster (NodePort: 마스터 노드 172.16.10.177:32200)
  # Loki보다 먼저 선언해야 Loki derivedFields에서 uid 참조 오류 없음
  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://172.16.10.177:32200
    editable: true
    jsonData:
      tracesToMetrics:
        datasourceUid: prometheus
        spanStartTimeShift: "-1h"
        spanEndTimeShift: "1h"
      nodeGraph:
        enabled: true
      search:
        hide: false
      serviceMap:
        datasourceUid: prometheus

  # Loki - K8s in-cluster (NodePort: 마스터 노드 172.16.10.177:30100)
  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://172.16.10.177:30100
    isDefault: false
    editable: true
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          name: TraceID
          matcherRegex: '"traceId":"([^"]+)"'
          url: '${__value.raw}'

        - datasourceUid: tempo
          name: SpanID
          matcherRegex: '"spanId":"([^"]+)"'
          url: '${__value.raw}'
