# 게이트웨이
{{- if .Values.gateway.enabled }}

# 게이트웨이 클래스
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: nginx
spec:
  controllerName: gateway.nginx.org/nginx-gateway-controller
---

# 게이트웨이 설정
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.gateway.namespace }}
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName }}
  listeners:

    # 80 포트
    {{- if .Values.gateway.http.enabled }}
    - name: http
      port: {{ .Values.gateway.http.port }}
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    {{- end }}

    # 환경 체크
    {{- range $env := .Values.gateway.environments }}

    # true인 환경
    {{- if $env.enabled }}

    # 반복문 진행
    {{- range $service := $env.services }}

    # 443 포트 적용
    - name: {{ $env.name }}-{{ $service.name }}-https
      port: 443
      protocol: HTTPS
      hostname: {{ $service.hostname }}
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ $env.tlsSecretName }}
            namespace: {{ $.Values.gateway.namespace }}
      allowedRoutes:
        namespaces:
          from: All
    # 반복문 종료
    {{- end }}

    # true 환경
    {{- end }}

    # 환경 체크
    {{- end }}

    {{- if .Values.gateway.listeners.argo.enabled }}
    # Argo CD
    - name: argo-https
      port: 443
      protocol: HTTPS
      hostname: {{ .Values.gateway.listeners.argo.domain }}
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ .Values.gateway.listeners.argo.tlsSecretName }}
            namespace: {{ .Values.gateway.namespace }}
      allowedRoutes:
        namespaces:
          from: All
    {{- end }}

{{- end }}
